#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vine
Version  : 1.3.0
Release  : 16
URL      : https://files.pythonhosted.org/packages/1c/e1/79fb8046e607dd6c2ad05c9b8ebac9d0bd31d086a08f02699e96fc5b3046/vine-1.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/1c/e1/79fb8046e607dd6c2ad05c9b8ebac9d0bd31d086a08f02699e96fc5b3046/vine-1.3.0.tar.gz
Summary  : Promises, promises, promises.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: vine-license = %{version}-%{release}
Requires: vine-python = %{version}-%{release}
Requires: vine-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : case

%description
vine - Python Promises
        =====================================================================
        
        |build-status| |coverage| |license| |wheel| |pyversion| |pyimp|

%package license
Summary: license components for the vine package.
Group: Default

%description license
license components for the vine package.


%package python
Summary: python components for the vine package.
Group: Default
Requires: vine-python3 = %{version}-%{release}

%description python
python components for the vine package.


%package python3
Summary: python3 components for the vine package.
Group: Default
Requires: python3-core

%description python3
python3 components for the vine package.


%prep
%setup -q -n vine-1.3.0
cd %{_builddir}/vine-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578638754
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/vine
cp %{_builddir}/vine-1.3.0/LICENSE %{buildroot}/usr/share/package-licenses/vine/aafbd18cc5180168ce48aa5f2022dc85a9f0e222
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/vine/aafbd18cc5180168ce48aa5f2022dc85a9f0e222

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
