#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vine
Version  : 1.1.4
Release  : 8
URL      : http://pypi.debian.net/vine/vine-1.1.4.tar.gz
Source0  : http://pypi.debian.net/vine/vine-1.1.4.tar.gz
Summary  : Promises, promises, promises.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: vine-python
BuildRequires : case
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
vine - Python Promises
        =====================================================================
        
        |build-status| |coverage| |license| |wheel| |pyversion| |pyimp|

%package python
Summary: python components for the vine package.
Group: Default

%description python
python components for the vine package.


%prep
%setup -q -n vine-1.1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1500252761
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1500252761
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
