#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vine
Version  : 1.1.3
Release  : 5
URL      : http://pypi.debian.net/vine/vine-1.1.3.tar.gz
Source0  : http://pypi.debian.net/vine/vine-1.1.3.tar.gz
Summary  : Promises, promises, promises.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: vine-python
BuildRequires : case
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
=====================================================================
vine - Python Promises
=====================================================================

%package python
Summary: python components for the vine package.
Group: Default

%description python
python components for the vine package.


%prep
%setup -q -n vine-1.1.3

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
